export const RPValues = {
  "10 Karat Gold": 1,
  "12 Karat Gold": 1,
  "18 Karat Gold": 1,
  "24 Karat Gold": 1,
  "8 Karat Gold": 1,
  "Acetic Acid": 7,
  "Aggregate": 1,
  "Alumina": 1,
  "Alumina Dust": 1,
  "Aluminium Ingot": 65,
  "Ammonia": 15,
  "Argon": 0,
  "Bauxite Residue": 1,
  "Black Dye": 1,
  "Boric Acid": 12,
  "Boron": 1,
  "Brass Ingot": 35,
  "Brick": 2,
  "Cat": 1,
  "Cement": 1,
  "Chair": 30,
  "Charged Lithium-Ion Battery": 1,
  "Cheap Water Bottle": 5,
  "Chlorine": 0.5,
  "Chunk Plank": 1,
  "Clay": 0.2,
  "Clay Brick": 1,
  "Coal": 1,
  "Coke Fuel": 9,
  "Concentrated Salt Solution": 1,
  "Concrete Block": 1,
  "Condensate": 0,
  "Contaminated Water": 0,
  "Control Rod": 1,
  "Copper Drill Head": 25,
  "Copper Ingot": 1.5,
  "Copper Mix": 1,
  "Copper Plate": 6,
  "Copper Powder": 1,
  "Copper Wire": 1,
  "Crankshaft": 35,
  "Crude Diesel": 1,
  "Crude Oil": 0.2,
  "Crushed Bauxite": 1,
  "Cut Oak Log": 1,
  "Deep Earth Fragment": 1,
  "Depleted UF6 Waste": 0,
  "Diesel": 2,
  "Dirty Lithium Sulfate": 1,
  "Distilled Water": 0.3,
  "Dynamite": 25,
  "Electric Motor": 200,
  "Electromagnet": 1,
  "Enriched UF6 Gas": 0,
  "Enriched UO2 Pellets": 1,
  "Ethanol": 2,
  "Ethylene": 0.2,
  "Exhaust": 0,
  "Ferroaluminium Alloy Ingot": 1,
  "Ferroaluminium Magnet": 120,
  "Filter": 1,
  "Filtered Water": 0.2,
  "Fission Byproducts": 0,
  "Fracking Oil": 0.2,
  "Galvanized Steel": 33,
  "Gasoline": 5,
  "GasolineE10": 13,
  "Gear": 20,
  "Gearbox": 50,
  "Glass": 14,
  "Gold Ingot": 70,
  "Gold Wire": 1,
  "Graphite-Iron Electrode": 1,
  "Graphite-Zinc Electrode": 1,
  "Gravel": 0.1,
  "Gunpowder": 1,
  "Hardened Plastic Casing": 20,
  "Hardened Plastic Pellets": 10,
  "Heavy Oil": 0.2,
  "High Pressure Steam": 0,
  "Hot Crude Oil": 0,
  "Hydrochloric Acid": 10,
  "Hydrofluoric Acid": 13,
  "Hydrogen": 0.5,
  "Hydrogen Sulfide": 0,
  "Impure Boron": 1,
  "Insulated Wire": 1,
  "Iron Coil": 4,
  "Iron Drill Head": 30,
  "Iron Ingot": 1,
  "Iron Mix": 1,
  "Iron Plate": 1,
  "Iron Plate²": 1,
  "Iron Powder": 1,
  "Lead Ingot": 1,
  "Leaded Gasoline": 23,
  "Light Oil": 0.1,
  "Limestone": 0.2,
  "Liquid Aluminium": 0,
  "Liquid Argon": 3,
  "Liquid Brass": 0,
  "Liquid Copper": 0,
  "Liquid Glass": 1,
  "Liquid Gold": 0,
  "Liquid Iron": 0,
  "Liquid Lead": 0,
  "Liquid Nitrogen": 3,
  "Liquid Oxygen": 3,
  "Liquid Sulfur": 0,
  "Lithium Battery Pack": 180,
  "Lithium Brine": 1,
  "Lithium Carbonate": 40,
  "Lithium Ore": 1,
  "Lithium Sulfate": 1,
  "LNG": 2,
  "Logic Plate": 1,
  "Low Enrichment Fuel Rod": 1,
  "Low Pressure Steam": 0,
  "Machine Oil": 4,
  "Medium Earth Fragment": 1,
  "MEG": 0.2,
  "Microchip Scrap": 1,
  "Mixed Fissile Nitrates": 1,
  "Mixed Fissile Oxides": 1,
  "Mixed Uranium Oxides": 1,
  "Molten Ferroaluminium Alloy": 1,
  "Molten Purple Gold": 1,
  "MOX Fuel Rod": 100,
  "Nails": 1,
  "Naphtha": 0.1,
  "Nitrogen": 0,
  "Oak Log": 1,
  "Oil Bottle": 20,
  "Oxygen": 0.5,
  "Packed Present": 1,
  "Paper": 7,
  "Paraxylene": 0.2,
  "Phosphorus Oxychloride": 0,
  "Plank²": 1,
  "Planks": 5,
  "Plastic Bottle": 30,
  "Plastic Pellets": 25,
  "Plutonium Oxide Pellets": 0,
  "Poor Quality Diesel": 1.5,
  "Powdered Tungsten": 1,
  "Powdered Tungsten Carbide": 1,
  "Present Box": 1,
  "PTA": 0.2,
  "Purple Gold Ingot": 100,
  "Raw Copper": 1,
  "Raw Gas": 0,
  "Raw Iron": 1,
  "Raw Lead": 1,
  "Raw Uranium": 1,
  "Raw Zinc": 1,
  "Raw Zirconium": 1,
  "Rawmix": 1,
  "Refined Diesel": 3,
  "Refined Diesel Bottle": 15,
  "Refined Gas": 0.01,
  "Reinforced Concrete Block": 4,
  "Reprocessed Uranium": 1,
  "Residue": 0,
  "Residue Bottle": 0,
  "Rich Soil": 1,
  "Rock": 1,
  "Rubber": 90,
  "Sand": 0.1,
  "Semiconductor": 30,
  "Shallow Earth Fragment": 1,
  "Silicon": 1,
  "Slightly Enriched UF6 Gas": 0,
  "Sodium Carbonate": 1,
  "Sodium Hydroxide Solution": 1,
  "Soil": 0.1,
  "Spent Fuel": 0,
  "Spent MOX Fuel": 0,
  "Standard Fuel Rod": 100,
  "Steam": 0,
  "Steel Coil": 1,
  "Steel Drill Head": 125,
  "Steel Ingot": 1,
  "Steel Plate": 18,
  "Steel Rod": 1,
  "Sulfur": 12,
  "Sulfur Dioxide": 0,
  "Sulfur Trioxide": 0,
  "Sulfuric Acid": 4,
  "Table Salt": 1,
  "Tetraethyllead": 7,
  "Tire": 40,
  "Tire Rim": 1,
  "Toy": 20,
  "Treated Raw Copper": 1,
  "Treated Raw Iron": 1,
  "Treated Rock": 1,
  "Tributyl Phosphate": 0,
  "Tungsten Carbide Drill Head": 225,
  "Tungsten Carbide Plate": 70,
  "Uncharged Lithium-Ion Battery": 1,
  "Unenriched UF6 Gas": 0,
  "Uranium": 1,
  "Water": 0,
  "Water Bottle": 20,
  "Water-Free Gas": 0,
  "Wet Concrete": 1,
  "Yellowcake": 5,
  "Zinc": 1,
  "Zinc Sulfate": 1,
  "Zirconium Chloride": 1,
  "Zirconium Dioxide": 1,
  "Zirconium Rod": 1
};
